theme = "dark_plus_joe"

[editor]
# line-number = "relative"
bufferline = "multiple"
rulers = [80]
# D   delete/change to end of line
[keys.normal]
"backspace" = ["delete_char_backward"]
# Y   yank current line
"Y" = ["extend_to_line_bounds", "yank"]
# -   delete current line
"minus" = ["extend_to_line_bounds", "delete_selection"]
# D   delete/change to end of line
"D" = ["extend_to_line_end", "delete_selection"]
"G" = ["goto_file_end"]      # also custom gj
"0" = ["goto_line_start"]    # gh
#"$" = ["goto_line_end"]     # gl
"ret" = ["goto_line_start", "move_line_down"]
"tab" = ["rotate_view"]
V = ["extend_to_line_bounds", "select_mode"]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
C-s = ":w"
esc = ["collapse_selection", "keep_primary_selection"]
# :e! = :reload
g = { k = "goto_file_start",  j = "goto_file_end" }

[keys.select]
g = { k = "goto_file_start",  j = "goto_file_end" }
"G" = ["goto_file_end"]      # also custom gj
"x" = ["delete_selection"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"


[editor.statusline]
right = [ "position", "position-percentage", "total-line-numbers"]

[editor.file-picker]
hidden = false

